name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: datetime-mcp:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Save Docker image
      run: docker save datetime-mcp:latest > datetime-mcp.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: datetime-mcp-docker-image
        path: datetime-mcp.tar
        retention-days: 7
